name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Update version and cache busting
      run: |
        # Update version with current timestamp
        VERSION=$(date +%Y%m%d%H%M)
        BUILD_TIME=$(date +%s)000
        
        # Update version.json
        jq --arg version "$VERSION" --arg buildTime "$BUILD_TIME" --arg lastModified "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)" \
          '.version = $version | .buildTime = ($buildTime | tonumber) | .lastModified = $lastModified' \
          version.json > version.json.tmp && mv version.json.tmp version.json
        
        # Update version.js
        sed -i "s/const VERSION = '[^']*';/const VERSION = '$VERSION';/" js/version.js
        sed -i "s/const BUILD_TIME = [0-9]*;/const BUILD_TIME = $BUILD_TIME;/" js/version.js
        
        # Update HTML files
        for file in *.html; do
          if [ -f "$file" ]; then
            sed -i "s/<meta name=\"version\" content=\"[^\"]*\" \/>/<meta name=\"version\" content=\"$VERSION\" \/>/" "$file"
            sed -i "s/<meta name=\"build-time\" content=\"[^\"]*\" \/>/<meta name=\"build-time\" content=\"$BUILD_TIME\" \/>/" "$file"
          fi
        done
        
        # Update service worker cache name
        sed -i "s/const CACHE_NAME = '[^']*';/const CACHE_NAME = 'haiphamcoder-v$VERSION';/" sw.js
        
        echo "Version updated to: $VERSION"
        echo "Build time: $BUILD_TIME"
        
    - name: Add cache busting to assets
      run: |
        # Add timestamp to CSS and JS files in HTML
        TIMESTAMP=$(date +%s)
        for file in *.html; do
          if [ -f "$file" ]; then
            # Add cache busting to CSS
            sed -i "s/href=\"css\/style\.css\"/href=\"css\/style.css?v=$TIMESTAMP\"/g" "$file"
            # Add cache busting to JS files
            sed -i "s/src=\"js\//src=\"js\//g" "$file"
            sed -i "s/\.js\"/.js?v=$TIMESTAMP\"/g" "$file"
            # Remove cache busting from CDN files
            sed -i "s/\.js?v=$TIMESTAMP\"/.js\"/g" "$file"
            sed -i "s/\.css?v=$TIMESTAMP\"/.css\"/g" "$file"
          fi
        done
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: haiphamcoder.github.io
